# Generated by Django 5.0.1 on 2024-02-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
