# Generated by Django 5.0.1 on 2024-01-22 07:54

import CustomUser.models
import CustomUser.storage
import CustomUser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=CustomUser.storage.OverwriteStorage(), upload_to=CustomUser.models.avatar_image_path, validators=[CustomUser.validators.validate_image]),
        ),
    ]
