# Generated by Django 5.0.1 on 2024-01-14 13:55

import CustomUser.models
import CustomUser.storage
import CustomUser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_customuser_avatar_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=CustomUser.storage.OverwriteStorage(), upload_to=CustomUser.models.avatar_image_path, validators=[CustomUser.validators.validate_image_ext, CustomUser.validators.validate_mime_type, CustomUser.validators.validate_image_size, CustomUser.validators.validate_image_dimensions]),
        ),
    ]
