# Generated by Django 5.0.1 on 2024-03-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_customuser_chat_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
