# Generated by Django 5.0.1 on 2024-03-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chat_online',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, default='offline', editable=False, max_length=255, null=True),
        ),
    ]
