# Generated by Django 5.0.1 on 2024-02-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingroom',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='matchmakingroom',
            name='player2',
        ),
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
        migrations.DeleteModel(
            name='MatchmakingRoom',
        ),
    ]
