version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    # In production, we will use expose instead of ports
    #expose:
    #  - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - transcendence

  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3000:3000"
  #  networks:
  #    - transcendence
  #  volumes:
  #    - ./frontend:/app
  #  command: npm start

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data:
