# game_config.py

CANVAS_WIDTH = 800
CANVAS_HEIGHT = 400
PADDLE_HEIGHT = 80
PADDLE_WIDTH = 10
BALL_WIDTH = 10
BALL_HEIGHT= 10
INITIAL_PADDLE_Y = CANVAS_HEIGHT // 2 - PADDLE_HEIGHT //2
INITIAL_BALL_X = CANVAS_WIDTH // 2 - BALL_WIDTH //2
INITIAL_BALL_Y = CANVAS_HEIGHT // 2 - BALL_HEIGHT //2
PADDLE_SPEED = 10.0
BALL_SPEED = 5.0
