# game_config.py

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
PADDLE_HEIGHT = 80
PADDLE_WIDTH = 10
BALL_WIDTH = 10
BALL_HEIGHT= 10
INITIAL_PADDLE_Y = SCREEN_HEIGHT // 2 - PADDLE_HEIGHT //2
INITIAL_BALL_X = SCREEN_WIDTH // 2
INITIAL_BALL_Y = SCREEN_HEIGHT // 2
PADDLE_SPEED = 10.0
BALL_SPEED = 5.0
