# Generated by Django 5.0.1 on 2024-01-16 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 22, 58, 858718, tzinfo=datetime.timezone.utc)),
        ),
    ]
