# Generated by Django 5.0.1 on 2024-02-17 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 0, 37, 32, 245163, tzinfo=datetime.timezone.utc)),
        ),
    ]
