# Generated by Django 5.0.1 on 2024-01-16 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0002_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 8, 23, 19, 102314, tzinfo=datetime.timezone.utc)),
        ),
    ]
