# Generated by Django 5.0.1 on 2024-01-16 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0003_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 47, 8, 695738, tzinfo=datetime.timezone.utc)),
        ),
    ]
