# Generated by Django 5.0.1 on 2024-02-19 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0004_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 4, 51, 59, 845066, tzinfo=datetime.timezone.utc)),
        ),
    ]
