# Generated by Django 5.0.1 on 2024-01-16 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0004_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 13, 1, 40, 685735, tzinfo=datetime.timezone.utc)),
        ),
    ]
