# Generated by Django 5.0.1 on 2024-02-21 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0007_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 11, 56, 54, 485722, tzinfo=datetime.timezone.utc)),
        ),
    ]
