# Generated by Django 5.0.1 on 2024-01-26 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0007_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 14, 33, 8, 1040, tzinfo=datetime.timezone.utc)),
        ),
    ]
