# Generated by Django 5.0.1 on 2024-02-07 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0008_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 10, 50, 13, 4693, tzinfo=datetime.timezone.utc)),
        ),
    ]
