# Generated by Django 5.0.1 on 2024-02-26 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0009_alter_twofactoremailmodel_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoremailmodel',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 4, 17, 59, 981893, tzinfo=datetime.timezone.utc)),
        ),
    ]
