#SCREEN
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600

#PADDLE
PADDLE_HEIGHT = int(SCREEN_HEIGHT / 5)
PADDLE_WIDTH = int(SCREEN_HEIGHT / 60)
PADDLE_BORDER_DISTANCE = int(SCREEN_HEIGHT / 30)
PADDLE_SPEED = int(SCREEN_HEIGHT / 40)

#BALL
BALL_SIZE = int(SCREEN_HEIGHT / 60)
BALL_SPEED = 300
BALL_SPEED_MAX = 500
BALL_SPEED_INCREASE = 0.25

#SCORE
SCORE_START = 0
SCORE_LIMIT = 3

#NETWORK
TICK_RATE = 30

#TIMER
READY_TIMER = 5
FORFEIT_TIMER = 15
EXIT_GAME_LOGIC_TIMER = 5