
#GAME
PLAYER_NB = 2

#SCREEN
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 640

if PLAYER_NB > 2:
    SCREEN_WIDTH = SCREEN_HEIGHT

#PADDLE
PADDLE_HEIGHT = SCREEN_HEIGHT * 0.2
PADDLE_WIDTH = SCREEN_HEIGHT * 0.02
PADDLE_BORDER_DISTANCE = SCREEN_HEIGHT * 0.04
PADDLE_SPEED = 10

#BALL
BALL_X = SCREEN_WIDTH // 2
BALL_Y = SCREEN_HEIGHT // 2
BALL_SPEED_RANGE = 50
BALL_SIZE = SCREEN_HEIGHT *0.02

#SCORE
SCORE_START = 0
SCORE_LIMIT = 3

#NETWORK
TICK_RATE = 60