# Generated by Django 5.0.1 on 2024-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='elo_history',
            field=models.JSONField(default=list),
        ),
    ]
