# Generated by Django 5.0.1 on 2024-02-19 02:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('max_participants', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ownerUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, related_name='tournament', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
