# Generated by Django 5.0.1 on 2024-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='round',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
