# Generated by Django 5.0.1 on 2024-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_matches_round_tournament_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='place_left',
            field=models.IntegerField(default=8, editable=False),
        ),
    ]
