# Generated by Django 5.0.1 on 2024-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_rename_is_draw_matches_is_in_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='room_url',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
