# Generated by Django 5.0.1 on 2024-03-21 09:54

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_matches_room_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTournament',
            fields=[
                ('winner', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('round', models.IntegerField(default=1, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('max_participants', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('localOwnerUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_local_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalMatch',
            fields=[
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('round', models.IntegerField(default=1, editable=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_url', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to='tournament.localtournament')),
            ],
        ),
    ]
