# Generated by Django 5.0.1 on 2024-03-21 10:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_localtournament_localmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournament',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
