# Generated by Django 5.0.1 on 2024-03-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_localtournament_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtournament',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='localtournament',
            name='name',
        ),
    ]
