# Generated by Django 5.0.1 on 2024-03-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_localtournament_max_participants_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalMatch',
            new_name='LocalMatches',
        ),
    ]
